#!/usr/bin/env python
import logging
import os
from typing import List

from feast import FeatureStore

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s %(message)s",
)
logger = logging.getLogger("feast_fraud.scripts.export_feature_catalog")


def _get_store(repo_path: str) -> FeatureStore:
    logger.info("Initializing FeatureStore", extra={"repo_path": repo_path})
    return FeatureStore(repo_path=repo_path)


def run(repo_path: str, out_path: str) -> None:
    store = _get_store(repo_path)

    entities = store.list_entities()
    feature_views = store.list_feature_views()
    feature_services = store.list_feature_services()

    lines: List[str] = []
    lines.append("# Feature Catalog\n")
    lines.append("")
    lines.append("This file is generated by `scripts/export_feature_catalog.py`.")
    lines.append(
        "Run `python scripts/export_feature_catalog.py` after updating the Feast repo."
    )
    lines.append("")
    lines.append("## Entities\n")
    for entity in sorted(entities, key=lambda e: e.name):
        lines.append(f"- **{entity.name}** — join_keys: {', '.join(entity.join_keys)}")
    lines.append("")

    lines.append("## FeatureViews\n")
    for fv in sorted(feature_views, key=lambda f: f.name):
        lines.append(f"### {fv.name}")
        lines.append(f"- Entities: {', '.join(e.name for e in fv.entities)}")
        if getattr(fv, "ttl", None) is not None:
            lines.append(f"- TTL: {fv.ttl}")
        source = getattr(fv, "source", None)
        if source is not None:
            # FileSource has `path`, PushSource has `batch_source.path`
            path = getattr(source, "path", None)
            if path is None and hasattr(source, "batch_source"):
                path = getattr(source.batch_source, "path", None)
            if path:
                lines.append(f"- Source path: `{path}`")
        lines.append("- Features:")
        for field in fv.schema:
            lines.append(f"  - `{field.name}` ({field.dtype})")
        lines.append("")

    lines.append("## FeatureServices\n")
    for fs in sorted(feature_services, key=lambda f: f.name):
        lines.append(f"### {fs.name}")
        lines.append("- Included features:")
        for fv_ref in fs.feature_view_projections:
            fv_name = fv_ref.name
            projected = [f.name for f in fv_ref.features]
            lines.append(f"  - **{fv_name}**: {', '.join(projected)}")
        lines.append("")

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    logger.info(
        "Feature catalog exported",
        extra={"out_path": out_path},
    )


def main() -> None:
    repo_path = os.getenv("FEAST_REPO_PATH", "feature_repo")
    out_path = os.path.join("docs", "feature_catalog.md")
    try:
        run(repo_path=repo_path, out_path=out_path)
    except Exception:  # noqa: BLE001
        logger.exception("export_feature_catalog_failed")
        raise


if __name__ == "__main__":
    main()